(async function (data, args, reqOptions) {
  if (!BeaconBar.user.metaData.menus.includes("EIM/AssignSubordinateBulk.aspx")) {
    return "It seems you don't have access. Please check with the HR Admin";
  }
  const indexList = args.empList.split(',').map(s => s.trim());

  async function payload(url) {
    const updateurl = await BeaconBar.executeFunction("updateUrlParams")(url);

    if (updateurl.updateUrl) {
      return {
        pageUrl: updateurl.updateUrl,
        param: updateurl.updateParams
      }
    } else {
      return {
        pageUrl: url,
        param: "IsShowButtons=1"
      }
    }
  }

  const updateUrlData = await payload("EIM/AssignSubordinateBulk.aspx");

  const url = `${reqOptions.sl}/${updateUrlData.pageUrl}`

  let viewState, viewStateGen, eventValidation, publicKey;

  window.direct.forEach(x => {
    if (indexList[0].includes(String(x.index))) {
      viewState = x.viewState;
      viewStateGen = x.viewStateGenerator;
      eventValidation = x.eventValidation;
      publicKey = x.publickey;
    }
  });
  if (args.supervisorType === "Direct") {
    const employeeResponse = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "",
      "__EVENTARGUMENT": "",
      "__VIEWSTATE": viewState,
      "__VIEWSTATEGENERATOR": viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdDirectSubordinates_ClientState": JSON.stringify({
        selectedIndexes: indexList,
        reorderedColumns: [],
        expandedItems: [],
        expandedGroupItems: [],
        expandedFilterItems: [],
        deletedItems: [],
        popUpLocations: {},
        draggedItemsIndexes: []
      }),
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$cmddireadd": "Change Supervisor",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const employeeResponse1 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "ctl00$body$rdoChangeToDirectSupervisor",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToDirectSupervisor",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const employeeResponse2 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "ctl00$body$chkDeassignFromExistingSupervisor",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse1.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse1.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse1.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse1.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToDirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const supervisorDetails = await BeaconBar.executeFunction("changeEmployeeSupervisor")(args.supervisorEmpId);

    const employeeResponse3 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "getSearchResultSup",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse2.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse2.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse2.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse2.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToDirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const empEnc = await BeaconBar.executeFunction("employeeEncryptId")(employeeResponse3.publicKey, window.employeeSelect.empNumber1);

    const employeeResponse4 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse3.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse3.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse3.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse3.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": empEnc,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl18$columnSelectCheckBox": "on",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToDirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": supervisorDetails.employeeId,
      "ctl00$body$txtNewSupervisorName": supervisorDetails.employeeName,
      "ctl00$body$txtNewSupervisorDesig": args.employeeDesignation,
      "ctl00$body$cmdIndireSave": "Save",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    return "sucessfully Change Supervisor..."
  } else if (args.supervisorType === "Indirect") {

    const employeeResponse = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "",
      "__EVENTARGUMENT": "",
      "__VIEWSTATE": viewState,
      "__VIEWSTATEGENERATOR": viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl04$columnSelectCheckBox": "on",
      "ctl00_body_grdInDirectSubordinates_ClientState": JSON.stringify({
        selectedIndexes: indexList,
        reorderedColumns: [],
        expandedItems: [],
        expandedGroupItems: [],
        expandedFilterItems: [],
        deletedItems: [],
        popUpLocations: {},
        draggedItemsIndexes: []
      }),
      "ctl00$body$cmddireadd": "Change Supervisor",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const employeeResponse1 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "ctl00$body$rdoChangeToIndirectSupervisor",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl02$ctl01$columnSelectCheckBox": "on",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl04$columnSelectCheckBox": "on",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToIndirectSupervisor",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const employeeResponse2 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "ctl00$body$chkDeassignFromExistingSupervisor",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse1.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse1.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse1.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse1.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToIndirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const supervisorDetails = await BeaconBar.executeFunction("changeEmployeeSupervisor")(args.supervisorEmpId);

    const employeeResponse3 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "getSearchResultSup",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse2.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse2.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse2.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse2.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl08$columnSelectCheckBox": "on",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToIndirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": "",
      "ctl00$body$txtNewSupervisorName": "",
      "ctl00$body$txtNewSupervisorDesig": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    const empEnc = await BeaconBar.executeFunction("employeeEncryptId")(employeeResponse3.publicKey, window.employeeSelect.empNumber1);


    const employeeResponse4 = await BeaconBar.executeFunction('module')({
      "scrollLeft": "0",
      "scrollTop": "0",
      "__EVENTTARGET": "",
      "__EVENTARGUMENT": "",
      "__LASTFOCUS": "",
      "__VIEWSTATE": employeeResponse3.viewState,
      "__VIEWSTATEGENERATOR": employeeResponse3.viewStateGen,
      "__VIEWSTATEENCRYPTED": "",
      "__EVENTVALIDATION": employeeResponse3.eventValidation,
      "ctl00$hdnDateFormat": "m/d/yy",
      "ctl00$hdnQuickmenu": "",
      "ctl00_body_RadWindowManager1_ClientState": "",
      "ctl00$body$txtActualEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtEmpNo": window.employeeSelect.empNumber1,
      "ctl00$body$txtPublicKey": employeeResponse3.publicKey,
      "ctl00$body$txtFullName": window.employeeSelect.fullname1,
      "ctl00$body$txtdesignation": window.employeeSelect.designation1,
      "ctl00$body$txtempnumber": empEnc,
      "ctl00$body$empSelectionIndividual$hdnEmpNumber": window.employeeSelect.empNumber1,
      "ctl00$body$empSelectionIndividual$hdnActiveInactiveToolbar": "",
      "ctl00$body$HFCurrTabIndex": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_grdDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_grdDirectSubordinates_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl02$ctl01$columnSelectCheckBox": "on",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "5",
      "ctl00_body_grdInDirectSubordinates_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00$body$grdInDirectSubordinates$ctl00$ctl04$columnSelectCheckBox": "on",
      "ctl00_body_grdInDirectSubordinates_ClientState": "",
      "ctl00$body$GrpSupervisorType": "rdoChangeToIndirectSupervisor",
      "ctl00$body$chkDeassignFromExistingSupervisor": "on",
      "ctl00$body$txtNewSupervisorNo": supervisorDetails.employeeId,
      "ctl00$body$txtNewSupervisorName": supervisorDetails.employeeName,
      "ctl00$body$txtNewSupervisorDesig": args.employeeDesignation,
      "ctl00$body$cmdIndireSave": "Save",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$GoToPageTextBox": "1",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_GoToPageTextBox_ClientState": "",
      "ctl00$body$GrdempSup$ctl00$ctl03$ctl01$ChangePageSizeTextBox": "10",
      "ctl00_body_GrdempSup_ctl00_ctl03_ctl01_ChangePageSizeTextBox_ClientState": "",
      "ctl00_body_GrdempSup_ClientState": ""
    }, url);

    return "sucessfully Change Supervisor..."

  }

})